### ISSUE TITLE
Danaides API v2.0.0

### ISSUE THREAD

**Issue by vikingphoenix** [ergopad/ergopad-api#518]
# Capabilities of Danaides
- track unspent boxes (main.py)
- perform useful aggregations each block change efficiently (api.py)
- support for ergowallet

# Brainstorm
_note: the description below needs to be updated_<br>

- [ ] move utxos extract (table) to api; call before materialized views
- [ ] consider storing block headers instead of box ids; quicker
- [ ] create transactions table from block headers; use to build utxos table
- [ ] update mempool during hibernate
- [ ] partition utxos by range ??

Danaides can import blockchain data regardless of what is queried out of it, but to be more consistent with the results and easier to interact with, the finalized logic should be moved to to endpoints. 

Currently the new endpoints should be:
/asset/balance (for token and currency balances)
/asset/info/{asset_id}

/token/summary (metrics including supply, in circulation, market cap, etc..)
/token/config (misc values like stake pool, token id...)
/token/status (emission, total staked..)
/token/staking (staking metrics for addresses)
/token/vesting (vesting metrics for addresses)
/token/info/{token_id}

/box/info/{box_id}

/market/tvl

/status (current danaides metrics: current unspent boxes, current height, last X block time avgs, etc..)

Considering validation endpoints (may be unnecessary):
/validate/address (check if valid but also that it exists)
/validate/unspent (is block unspent

More functionality to split out (currently unneeded):
- burn/mint token (other apps that do this currently)
- compound (handled offchain with bots)
- snapshot (currently useful)
- consolidate assets to single address (should prob be a wallet function)
- add erg to transaction to bump priority
