### ISSUE TITLE
Paideia: Remove id from member slugs

### ISSUE THREAD

**Issue by noob77777** [ergopad/ergopad-api#592]
- Add unique constraints to username per dao (requires update across psql and api(
- Url should be `{dao}/members/{username}`

### Subtasks
- [x] Constraint UNIQUE in postgres
- [x] paideia-api update
- [ ] update paideia-app redirects
